server:
  port: 8086
spring:
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost/sys?useLL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=true
mybatis: #\u914D\u7F6E\u522B\u540D
  type-aliases-package: com.newer.demo2.domain
  mapper-locations: classpath:com/newer/demo2/mapper/*.xml




